// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQgKa1Hw6ueK_Cv9IOpMMKeB0ZwBU_PY',
    appId: '1:553033882338:web:619e57d31f49706e9f5cbb',
    messagingSenderId: '553033882338',
    projectId: 'first-step-3fbf8',
    authDomain: 'first-step-3fbf8.firebaseapp.com',
    storageBucket: 'first-step-3fbf8.appspot.com',
    measurementId: 'G-J8JS0JGJG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXAFJumydJaZ06CXzjDO3hiZiCnVsfoKQ',
    appId: '1:553033882338:android:567635cb0d58a9779f5cbb',
    messagingSenderId: '553033882338',
    projectId: 'first-step-3fbf8',
    storageBucket: 'first-step-3fbf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifm2VOeqFCRaunBkbF_UF7oVS_uME4Cc',
    appId: '1:553033882338:ios:9c6bb40a18b900659f5cbb',
    messagingSenderId: '553033882338',
    projectId: 'first-step-3fbf8',
    storageBucket: 'first-step-3fbf8.appspot.com',
    iosBundleId: 'com.example.firstStep',
  );
}
